### PR TITLE
Add contacts search

### PR DESCRIPTION
**Pull request by hursey013**
Interactive search of agency contacts based on json data file.

Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/pra.gov/bh-contacts-search/contact/

Uses the agency's name, agency abbreviation, and office name as the search fields.

### CODE REVIEW

**Comment by cmajel** [comment]
@hursey013 One thing I notice is that there is no filtered dropdown when I search, it just displays the  the results preview. Is that something that will be added later? 

Realize also that this was in the earlier invisions, but not the most recent. [Updated view here.](https://gsa.invisionapp.com/share/UYR6YCKEC9F#/354249476_Results-Options)

**Comment by hursey013** [comment]
@cmajel Ah, I see, I was looking at the mockup from the user testing I think. Yeah the way it works now is it would just show a list of matching results below as the user types, sort of bypassing the need to click an agency in the dropdown. So is the idea that we would list agencies even if they don't have a contact?

Adding in the dropdown step will require some additional logic, so I guess my suggestion would be if you find the current implementation acceptable, I would merge it in as is, and then we can create a follow on task to iterate on the exact interaction.

**Comment by cmajel** [comment]
@hursey013 ah ok cool. I've added an issue to build out the dropdown here (#43) but agree that this is fine for demo purposes. I'll approve this PR. 

I would suggest that the filtered list only show agencies that have listings, but users can be allowed to submit a query not shown on the list and receive a "no results" card. What do you think?

**Comment by hursey013** [comment]
Yeah, that is how it works now I believe. If you search for `foobar` you get `No results found`, but we could expand that card to include more information about how to have your agency added. Either way, happy to continue iterating on this with you, might make sense to set up a quick chat to make sure we are on the same page post site freeze.

**Pull request merged**
